name: Retrieve recent blog posts, tech tips and events
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  update--profile-readme:
    name: Update GitHub Profile README with recent blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 10
          feed_list: "https://kristhecodingunicorn.com/post/index.xml"
          
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 10
          comment_tag_name: "TECH-TIPS-LIST"
          feed_list: "https://kristhecodingunicorn.com/techtips/index.xml"

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 10
          comment_tag_name: "EVENTS-LIST"
          feed_list: "https://politepol.com/fd/QSndeAikuwqO"
          disable_sort: true